### PR TITLE
Fix target flag being set on dependencies

### PR DESCRIPTION
**Pull request by jschornick**
Hi @Morganamilo!

Starting with Paru 1.3.0, I began having some weird issues clearing packages that should have been orphans. Checking my pacman log, I tracked it down to the fact that for AUR packages installed via Paru 1.3.0, some of the dependencies were being installed with the `--asexplicit` flag. In the past, these were always being installed with `--asdeps`, which seems correct. 

Looking more closely, there seems to be a bug in how your package resolver is building the actions for dependencies. I whipped up a quick test that simulates the bug I'm seeing, and this is the resulting patch. 

And FYI, a bunch of your tests were failing (for me) on a fresh clone of the repo. As far as I know, no additional tests fail as a result of this my changes.

--- 

Within `resolve_aur_pkg()`, the `AurPackage` structs added to the build
action list are only for the dependent packages. However, the first call
to `resolve_aur_pkg()` can be called with `target=true`, and this value was
being used to set the target flag for each of these `AurPackages`. This is
incorrect and should simply be set to false for all dependencies.

Any recursive dependencies were being set correctly, as
`resolve_aur_pkg()` was explicitly called with `target=false`.

Since the primary target package is added to the build action list
separately in `resolve()`, this is the only place were the AurPackage
needs `target=true`, and is handled independently of `resolve_aur_pkg()`.

To fix, remove the target logic from `resolve_aur_pkg()` entirely. Also
rename the function to better indicate that it is only resolving
dependencies.

Also rename some confusing aliasing of the pkg parameter.

Finally, add a test to catch the original bug.

### CODE REVIEW

**Comment by Morganamilo** [comment]
Code looks good. I don't like how the test works though. especially that it prints. Add a `targets` field to `TestActions` and use that to compare. You could just make `targets` a usize and check that there's one target. Or make it a `Vec<Strring>` to actually check the name if you really want to.

As for the tests failing. That's cause the localdb changed I believe. I've not got around to fixing it.

**Comment by jschornick** [comment]
Thanks for the quick reply!

I can totally admit the test is ugly... just a quick-and-dirty hack to verify my change actually fixed the right bug. I blame the bad style on the fact that I have near zero rust experience. 

I appreciate the tips and feedback, and I will try to update this PR with a cleaned-up version of the test later today.

**Comment by jschornick** [comment]
I rewrote the test using `TestActions` per your recommendation. Much cleaner now!

Please take a quick look and let me know if it needs any more tweaking.

**Comment by Morganamilo** [comment]
Looks good now, thanks.

**Pull request merged**
