### PR TITLE
add flag for resolving all recursive deps

### PR DESCRIPTION
**Pull request by acxz**
Solves #7

### CODE REVIEW

**Comment by Morganamilo** [comment]
I still don't really think you even know what you're really trying to do here. Like I said resolving deps recursively is the whole point of a dependency solver.

The --rebuild=tree flag in yay just tells the resolver to not skip aur packages that are already installed. That's not at all what this code does. The naming and description of the flag is also very misleading.

**Comment by acxz** [comment]
> The naming and description of the flag is also very misleading.

Should I change the flag from `ALL_DEPS` to `RECURSIVE_DEPS` or `TREE_DEPS`?
Instead of `Resolve all recursive dependencies.` maybe `Do not skip recursive dependencies.` would be more apt?

I guess my reasoning was as follows: The function `should_skip_aur_pkg` is the function that the resolver uses to determine which aur packages should be skipped or not. And by adding a flag for rebuildtree, i.e. `ALL_DEPS`, we can use that flag to ensure that no recursive dependency is skipped by the resolver. Hence the
```
+            if self.flags.contains(Flags::ALL_DEPS) {
+                return false;
+            }
```

Thank you for the help so far, but I guess it seems like I still need more guidance.

**Comment by Morganamilo** [comment]
> maybe Do not skip recursive dependencies. would be more apt?

I'm not sure why you keep bringing up "recursive", recursion doesn't really have anything to do with this.

I would name it `RESOLVE_INSTALLED_AUR_DEPS` "Don't skip already installed AUR dependencies".

**Comment by acxz** [comment]
> I'm not sure why you keep bringing up "recursive", recursion doesn't really have anything to do with this.

I see, I think I understand now, basically all the deps are the recursive deps, so the use of recursion is not appropriate.

> I would name it RESOLVE_INSTALLED_AUR_DEPS "Don't skip already installed AUR dependencies".

Done!

Do I need to do anything else in terms of bumping version numbers etc. for paru to recognize when this crate gets updated?

**Comment by FoxieDev** [comment]
The latest version of this code doesn't achieve what you wish it to. You have added this flag to the part of the code that deals with skipping checking, rather than anything to do with if a package is installed or not. The basic premise of the --rebuildtree flag is that it will still rebuild and install a package if it is installed. the flag you added only skips the check for if it should resolve the dependency.
I understand your willingness to help, but right now @Morganamilo has many things to be doing, and this code is not entirely her main focus. This is not a "won't implement" nor is it a brushing off of your code and suggestions, but this is a request that we deal with this in a few weeks? @Morganamilo already has this on her todo, and so attempting to implement it over and over in a way that's not really implementing what you think it is, won't help for now.
v2 already has this as a milestone, and it'll be implemented by @Morganamilo then, so I'd recommend just letting her get to it in time, as all she'll be doing is reimplementing it then anyways.

Honestly I do love your enthusiasm for the project, but there's no kind way to say "this code doesn't do what you think it does, and the main dev is gonna replace it in a few weeks anyway" So i really do hope this doesn't come off as too harsh?

**Comment by acxz** [comment]
> So i really do hope this doesn't come off as too harsh?

No no, not at all. In fact, I appreciate you letting me know as I would rather let people that already know what they are doing to do the task. I am sure that is much more helpful than trying to guide someone else through the process, especially considering that someone is new to the codebase (and tbh struggling a bit to get familiar with it as well).

**Comment by FoxieDev** [comment]
I'm glad! I was sat there looking at this PR for so long trying to work out the best way to say "your work is kind of in vain" without it sounding cruel!
I'll see if I can remember to ping you once v2 goes live?

**Comment by Morganamilo** [comment]
https://github.com/Morganamilo/aur-depends/commit/adae47712fa003bc0d234d355308dc5709fa69b3

**Pull request closed without merging**
